# Generated by Django 5.2.4 on 2025-07-31 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FocoEstrategico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoInvestigacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Investigador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('rol_externo', models.CharField(help_text='Ej: Asesor Metodológico, Jurado Evaluador', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramaAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consecutivo', models.IntegerField(blank=True, null=True, unique=True, verbose_name='N° Consecutivo')),
                ('titulo', models.CharField(max_length=500, verbose_name='Título')),
                ('pais', models.CharField(default='Colombia', max_length=100, verbose_name='País')),
                ('es_proyecto_estrategico', models.BooleanField(default=False, verbose_name='¿Es Proyecto Estratégico?')),
                ('otra_afiliacion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Otra afiliación (Área o Servicio)')),
                ('investigador_principal', models.CharField(blank=True, max_length=200, null=True, verbose_name='Investigador Principal')),
                ('participacion_otra_entidad', models.BooleanField(default=False, verbose_name='¿Participa otra entidad?')),
                ('presentado_a_convocatoria', models.BooleanField(default=False, verbose_name='¿Presentado a Convocatoria?')),
                ('financiado_por_convocatoria', models.BooleanField(default=False, verbose_name='¿Financiado por Convocatoria?')),
                ('duracion_meses', models.IntegerField(blank=True, null=True, verbose_name='Duración del Proyecto (meses)')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Activo?')),
                ('progreso_construccion', models.IntegerField(default=0, verbose_name='Progreso Construcción (%)')),
                ('progreso_recoleccion', models.IntegerField(default=0, verbose_name='Progreso Recolección de Datos (%)')),
                ('progreso_analisis', models.IntegerField(default=0, verbose_name='Progreso Análisis de Datos (%)')),
                ('progreso_documento_final', models.IntegerField(default=0, verbose_name='Progreso Documento Final (%)')),
                ('progreso_sometimiento', models.IntegerField(default=0, verbose_name='Progreso Sometimiento (%)')),
                ('progreso_publicacion', models.IntegerField(default=0, verbose_name='Progreso Publicación (%)')),
                ('aprobacion_cei', models.BooleanField(default=False, verbose_name='Aprobación CEI UNISANITAS')),
                ('consecutivo_ceifus', models.CharField(blank=True, max_length=50, null=True, verbose_name='Consecutivo CEIFUS')),
                ('fecha_ceifus', models.DateField(blank=True, null=True, verbose_name='Fecha CEIFUS')),
                ('asesores', models.ManyToManyField(blank=True, related_name='proyectos_asesorados', to='proyectos.investigador')),
                ('epidemiologo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_epidemiologo', to=settings.AUTH_USER_MODEL, verbose_name='Epidemiólogo')),
                ('foco_estrategico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyectos.focoestrategico')),
                ('grupos_investigacion', models.ManyToManyField(blank=True, to='proyectos.grupoinvestigacion')),
                ('jurados', models.ManyToManyField(blank=True, related_name='proyectos_evaluados', to='proyectos.investigador')),
                ('programas_postgrado', models.ManyToManyField(blank=True, related_name='proyectos_postgrado', to='proyectos.programaacademico')),
                ('programas_pregrado', models.ManyToManyField(blank=True, related_name='proyectos_pregrado', to='proyectos.programaacademico')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_producto', models.CharField(max_length=255)),
                ('tipo_principal', models.CharField(choices=[('nuevo_conocimiento', 'Generación de Nuevo Conocimiento'), ('desarrollo_innovacion', 'Desarrollo Tecnológico e Innovación'), ('apropiacion_social', 'Apropiación Social del Conocimiento'), ('formacion_rrhh', 'Formación de Recurso Humano')], max_length=50)),
                ('subtipo_especifico', models.CharField(help_text='Ej: Artículo A1, Software, Ponencia, Tesis de Grado', max_length=100)),
                ('estado', models.CharField(choices=[('desarrollo', 'En Desarrollo'), ('sometido', 'Sometido a Evaluación'), ('publicado', 'Publicado/Finalizado'), ('reconocido', 'Reconocido')], default='desarrollo', max_length=20)),
                ('referencia', models.TextField(blank=True, help_text='DOI, ISBN, URL, nombre de la revista, etc.')),
                ('reconocimiento_universidad', models.BooleanField(default=False)),
                ('proyecto_padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='proyectos.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Avance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_avance', models.CharField(choices=[('inicio', 'Inicio Formal del Proyecto'), ('asignacion_asesor', 'Asignación de Asesor'), ('sometimiento_comite', 'Sometimiento a Comité de Ética'), ('aprobacion_comite', 'Aprobación de Comité de Ética'), ('entrega_parcial', 'Entrega Parcial'), ('correcciones', 'Recepción de Correcciones'), ('presentacion_evento', 'Presentación en Evento'), ('sometimiento_publicacion', 'Sometimiento de Artículo/Producto'), ('finalizacion', 'Finalización/Cierre de Proyecto')], max_length=50)),
                ('fecha_avance', models.DateField()),
                ('descripcion', models.TextField(help_text='Detalles del avance, observaciones, etc.')),
                ('autor_del_avance', models.ForeignKey(help_text='Usuario que registra el avance.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avances', to='proyectos.proyecto')),
            ],
            options={
                'ordering': ['-fecha_avance'],
            },
        ),
    ]
